# GitLab CI/CD для Velo Leasing Bot

stages:
  - test

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

# Простое тестирование кода
test:
  stage: test
  image: python:3.11-slim
  script:
    - echo "🧪 Простая проверка синтаксиса..."
    - python -m py_compile main.py
    - echo "✅ Основной файл корректен"
    - echo "🚀 Проект готов к работе!"
  only:
    - main
    - merge_requests

# ОСТАЛЬНЫЕ STAGES ВРЕМЕННО ОТКЛЮЧЕНЫ
# Раскомментируйте когда настроите переменные окружения

# build:
#   stage: build
#   image: docker:latest
#   script:
#     - echo "🔨 Сборка отключена до настройки переменных"

# deploy:
#   stage: deploy
#   script:
#     - echo "🚀 Деплой отключен до настройки переменных"
