# GitLab CI/CD для Velo Leasing Bot

stages:
  - test
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"

# Тестирование кода
test:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install -r requirements.txt
  script:
    - echo "🧪 Запуск тестов..."
    - python -m py_compile main.py
    - python -m py_compile bot/**/*.py
    - python -m py_compile database/**/*.py
    - echo "✅ Синтаксис Python корректен"
  only:
    - main
    - merge_requests

# Сборка Docker образа
build:
  stage: build
  image: docker:latest
  services:
    - docker:dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "🔨 Сборка Docker образа..."
    - docker build -t $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA .
    - docker build -t $CI_REGISTRY_IMAGE:latest .
    - docker push $CI_REGISTRY_IMAGE:$CI_COMMIT_SHA
    - docker push $CI_REGISTRY_IMAGE:latest
  only:
    - main

# Деплой на продакшен (ручной запуск)
deploy_production:
  stage: deploy
  image: docker:latest
  script:
    - echo "🚀 Деплой на продакшен..."
    - echo "Здесь будут команды для деплоя на ваш сервер"
    # Пример команд:
    # - ssh $DEPLOY_USER@$DEPLOY_HOST "docker pull $CI_REGISTRY_IMAGE:latest"
    # - ssh $DEPLOY_USER@$DEPLOY_HOST "docker-compose -f /path/to/docker-compose.yml up -d"
  environment:
    name: production
    url: https://your-bot-domain.com
  when: manual
  only:
    - main

# Деплой на staging (автоматический)
deploy_staging:
  stage: deploy
  image: docker:latest
  script:
    - echo "🔄 Деплой на staging..."
    - echo "Автоматический деплой тестовой версии"
  environment:
    name: staging
    url: https://staging.your-bot-domain.com
  only:
    - main

# Проверка безопасности (опционально)
security_scan:
  stage: test
  image: python:3.11-slim
  before_script:
    - pip install safety bandit
  script:
    - echo "🔒 Проверка безопасности..."
    - safety check -r requirements.txt
    - bandit -r . -f json -o bandit-report.json || true
  artifacts:
    reports:
      security:
        - bandit-report.json
  allow_failure: true
  only:
    - main
    - merge_requests
