# GitLab CI/CD временно отключен
# Раскомментируйте когда будете готовы к настройке

# stages:
#   - test

# simple_test:
#   stage: test
#   image: python:3.11-slim
#   script:
#     - echo "✅ Проект загружен успешно!"
#   only:
#     - main

# ========================================
# ПОЛНАЯ ВЕРСИЯ CI/CD (раскомментируйте когда нужно)
# ========================================

# CI/CD временно отключен до верификации аккаунта GitLab
# Раскомментируйте когда верифицируете аккаунт

# stages:
#   - info

# # Простое информационное сообщение
# project_info:
#   stage: info
#   image: alpine:latest
#   script:
#     - echo "🚀 Velo Leasing Bot проект"
#     - echo "✅ Код успешно загружен на GitLab"
#     - echo "📋 Готовые компоненты:"
#     - echo "   - Система регистрации пользователей"
#     - echo "   - Верификация документов" 
#     - echo "   - Административная панель"
#     - echo "   - Модели базы данных"
#     - echo "   - Docker конфигурация"
#     - echo ""
#     - echo "🔄 В разработке:"
#     - echo "   - Интеграция ЮKassa"
#     - echo "   - AI обработка документов"
#     - echo "   - Генерация договоров"
#     - echo ""
#     - echo "🎯 Проект готов к дальнейшей разработке!"
#   rules:
#     - if: $CI_COMMIT_BRANCH == "main"