# GitLab CI/CD отключен до верификации аккаунта
# Этот файл содержит минимальную валидную конфигурацию, которая ничего не делает

workflow:
  rules:
    - when: never  # Никогда не запускать пайплайны